- name: Check for swap file existence
  ansible.builtin.stat:
    path: /swapfile
  register: swap_file

- name: Create and activate swap
  when: not swap_file.stat.exists
  block:
    - name: Create swap file
      ansible.builtin.command:
        cmd: "fallocate -l 2G /swapfile"
      changed_when: true

    - name: Set swap file permissions
      ansible.builtin.file:
        path: /swapfile
        mode: "0600"

    - name: Format swap file
      ansible.builtin.command:
        cmd: "mkswap /swapfile"
      changed_when: true

    - name: Add swap file to fstab
      ansible.posix.mount:
        src: /swapfile
        name: swap
        fstype: swap
        state: present
        opts: default

    - name: Activate swap
      ansible.builtin.command:
        cmd: "swapon -a"
      changed_when: true
