- name: (Re-)Start etcd
  ansible.builtin.systemd_service:
    name: etcd
    state: restarted
    enabled: true
    daemon_reload: true
  register: etcd_service_state
  until: etcd_service_state.ActiveState == "active"
  retries: 20
  delay: 5
