- name: Provisioning servers
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: hetzner_provision
    - role: hetzner_dns
    - role: hetzner_volumes

- name: Install base system
  hosts: _managed
  any_errors_fatal: true
  roles:
    - role: base_rsyslog
    - role: base_swap
    - role: base_ufw
    - role: base_ssh
    - role: base_msmtp
    - role: base_unattended-upgrades
    - role: network_wireguard
      vars:
        wg_peers: "{{ groups['_managed'] }}"

# - name: Install Kubernetes Control-Plane
#   hosts: controlplane
#   any_errors_fatal: true
#   roles:
#     - control_etcd

# - name: Cleanup cluster
#   gather_facts: false
#   hosts: localhost
#   roles:
#     - hetzner_cleanup
