- name: Provisioning servers
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: hetzner_provision
    - role: hetzner_dns
    - role: hetzner_volumes

- name: Install base system
  hosts: _managed:!_remove
  any_errors_fatal: true
  roles:
    - role: base_rsyslog
    - role: base_swap
    - role: base_ufw
    - role: base_ssh
    - role: base_msmtp
    - role: base_unattended-upgrades
    - role: base_containerd

- name: Setup network
  hosts: _managed
  any_errors_fatal: true
  roles:
    - role: network_wireguard
      vars:
        wg_peers: "{{ groups['_managed'] }}"

- name: Install Kubernetes Control-Plane
  hosts: _control
  any_errors_fatal: true
  roles:
    - role: control_etcd
      vars:
        job: create

- name: Cleanup Kubernetes Control-Plane
  hosts: _control
  any_errors_fatal: true
  roles:
    - role: control_etcd
      vars:
        job: cleanup

- name: Cleanup Network
  hosts: _managed
  any_errors_fatal: true
  roles:
    - role: network_wireguard
      vars:
        wg_peers: >-
          {{
            hostvars
            | dict2items
            | selectattr('key', 'in', groups['_managed'])
            | selectattr('value.state', 'ne', 'remove')
            | map(attribute='key')
            | list
          }}

- name: Cleanup servers
  gather_facts: false
  hosts: localhost
  roles:
    - cleanup_hetzner
