- name: Provisioning servers
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  roles:
    - role: hetzner_provision
    - role: hetzner_dns
    - role: hetzner_volumes

- name: Install base system
  hosts: _managed
  any_errors_fatal: true
  roles:
    - role: base_rsyslog
      when: state != "remove"
    - role: base_swap
      when: state != "remove"
    - role: base_ufw
      when: state != "remove"
    - role: base_ssh
      when: state != "remove"
    - role: base_msmtp
      when: state != "remove"
    - role: base_unattended-upgrades
      when: state != "remove"
    - role: network_wireguard
      vars:
        wg_peers: "{{ groups['_managed'] }}"

- name: Install Kubernetes Control-Plane
  hosts: _control
  any_errors_fatal: true
  roles:
    - control_etcd

- name: Cleanup servers
  gather_facts: false
  hosts: localhost
  roles:
    - cleanup_hetzner
