- name: Provisioning servers
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  roles:
    - hetzner_provision
    - hetzner_dns
    - hetzner_volumes

- name: Install base system
  hosts: managed
  any_errors_fatal: true
  roles:
    - base_swap
    - base_ufw
    - base_ssh
    - base_msmtp
    - base_unattended-upgrades
    - network_wireguard

- name: Install Kubernetes Control-Plane
  hosts: controlplane
  any_errors_fatal: true
  roles:
    - control_etcd

- name: Cleanup cluster
  gather_facts: false
  hosts: localhost
  roles:
    - hetzner_cleanup
