- name: Rename old/not managed servers
  connection: local
  delegate_to: localhost
  when: inventory_hostname in groups["unmanaged"] and inventory_hostname != old_name
  ansible.builtin.uri:
    url: "https://api.hetzner.cloud/v1/servers/{{ hetzner_id }}"
    method: PUT
    headers:
      Authorization: "Bearer {{ hetzner.token.cloud }}"
      Content-type: "application/json"
    body_format: json
    body:
      name: "{{ inventory_hostname }}"

- name: Adding SSH keys
  delegate_to: localhost
  connection: local
  run_once: true
  hetzner.hcloud.ssh_key:
    name: "{{ item.key }}"
    public_key: "{{ item.value }}"
    state: present
    api_token: "{{ hetzner.token.cloud }}"
  loop: "{{ ssh_keys | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create Server Block
  when: inventory_hostname in groups['managed'] and create
  block:
    - name: Create server
      connection: local
      delegate_to: localhost
      hetzner.hcloud.server:
        api_token: "{{ hetzner.token.cloud }}"
        name: "{{ inventory_hostname }}"
        server_type: "{{ type }}"
        image: "{{ image }}"
        state: started
        location: "{{ location }}"
        ssh_keys: "{{ ssh_keys.keys() | list }}"
        enable_ipv6: true
        enable_ipv4: false
        labels:
          image: "{{ image }}"
          server_type: "{{ type }}"
          location: "{{ location }}"
          is_control: "{{ is_control | lower }}"
          is_worker: "{{ is_worker | lower }}"
          internal_ip: "{{ internal_ip }}"
      register: server

    - name: Get new IPv6
      connection: local
      when: server.changed and server.hcloud_server.ipv6 is defined
      ansible.builtin.set_fact:
        ansible_host: "{{ server.hcloud_server.ipv6 | ansible.utils.ipaddr('1') | ansible.utils.ipaddr('address') }}"

    - name: Wait for network to come up fully
      connection: local
      delegate_to: localhost
      ansible.builtin.wait_for:
        port: 22
        search_regex: OpenSSH
        host: "{{ ansible_host }}"
